### ISSUE TITLE
inport rdp (create new client) error issue v 2.2

### ISSUE THREAD

**Issue by Zerglrisk** [jaysonragasa/MultiRDPClient.NET#2]
![image](https://user-images.githubusercontent.com/8271831/81896923-812b2700-95f0-11ea-9f74-d26f966861ca.png)

이 대화 상자 대신 JIT(Just-in-time) 디버깅을 호출하는
방법에 대한 자세한 내용은 이 메시지의 뒷부분을 참조하십시오.

************** 예외 텍스트 **************
System.Exception: An error occured while executing a query.
Exception Message: database is locked
database is locked
Stack Trace:
   위치: System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   위치: System.Data.SQLite.SQLiteDataReader.NextResult()
   위치: System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   위치: System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   위치: System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   위치: Database.Database.ExecuteNonQuery(String sql_query, SQLiteParameter[] parameters) 파일 F:\WinForms\MultiRDPClient.NET\Database\Database.cs:줄 124
   위치: Database.Servers.Save(ServerDetails server_details) 파일 F:\WinForms\MultiRDPClient.NET\Database\Servers.cs:줄 132
   위치: MultiRemoteDesktopClient.ImportWindow.btnStart_Click(Object sender, EventArgs e) 파일 F:\WinForms\MultiRDPClient.NET\RemoteDesktopClient\Forms\ImportWindow.cs:줄 138
   위치: System.Windows.Forms.Control.OnClick(EventArgs e)
   위치: System.Windows.Forms.Button.OnClick(EventArgs e)
   위치: System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   위치: System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   위치: System.Windows.Forms.Control.WndProc(Message& m)
   위치: System.Windows.Forms.ButtonBase.WndProc(Message& m)
   위치: System.Windows.Forms.Button.WndProc(Message& m)
   위치: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 로드된 어셈블리 **************
mscorlib
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4180.0 built by: NET48REL1LAST_B
    코드베이스: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MultiRemoteDesktopClient
    어셈블리 버전: 2.2.0.23940
    Win32 버전: 2.2.0.0
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/MultiRemoteDesktopClient.exe
----------------------------------------
System.Windows.Forms
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4150.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4001.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.3752.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.AppCenter.Analytics
    어셈블리 버전: 0.0.0.0
    Win32 버전: 3.2.1
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/Microsoft.AppCenter.Analytics.DLL
----------------------------------------
Microsoft.AppCenter
    어셈블리 버전: 0.0.0.0
    Win32 버전: 3.2.1
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/Microsoft.AppCenter.DLL
----------------------------------------
Microsoft.AppCenter.Crashes
    어셈블리 버전: 0.0.0.0
    Win32 버전: 3.2.1
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/Microsoft.AppCenter.Crashes.DLL
----------------------------------------
Microsoft.VisualBasic
    어셈블리 버전: 10.0.0.0
    Win32 버전: 14.8.3752.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4180.0 built by: NET48REL1LAST_B
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.3752.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.3752.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    어셈블리 버전: 12.0.0.0
    Win32 버전: 12.0.2.23222
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/Newtonsoft.Json.DLL
----------------------------------------
SQLitePCLRaw.batteries_v2
    어셈블리 버전: 2.0.2.669
    Win32 버전: 2.0.2.669
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/SQLitePCLRaw.batteries_v2.DLL
----------------------------------------
netstandard
    어셈블리 버전: 2.0.0.0
    Win32 버전: 4.8.3752.0
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
SQLitePCLRaw.core
    어셈블리 버전: 2.0.2.669
    Win32 버전: 2.0.2.669
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/SQLitePCLRaw.core.DLL
----------------------------------------
SQLitePCLRaw.provider.dynamic_cdecl
    어셈블리 버전: 2.0.2.669
    Win32 버전: 2.0.2.669
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/SQLitePCLRaw.provider.dynamic_cdecl.DLL
----------------------------------------
System.Memory
    어셈블리 버전: 4.0.1.1
    Win32 버전: 4.6.27617.02
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/System.Memory.DLL
----------------------------------------
SQLitePCLRaw.nativelibrary
    어셈블리 버전: 2.0.2.669
    Win32 버전: 2.0.2.669
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/SQLitePCLRaw.nativelibrary.DLL
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.3752.0
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    어셈블리 버전: 4.0.4.1
    Win32 버전: 4.6.26919.02
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Runtime
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.3752.0
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Management
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.3752.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Runtime.Remoting
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.3752.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Deployment
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.3752.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
System.Deployment.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.3752.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Deployment.resources/v4.0_4.0.0.0_ko_b03f5f7f11d50a3a/System.Deployment.resources.dll
----------------------------------------
System.Runtime.Serialization
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4180.0 built by: NET48REL1LAST_B
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Numerics
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.3752.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4121.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
mscorlib.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.3752.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Database
    어셈블리 버전: 1.0.1122.2011
    Win32 버전: 1.0.1122.2011
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/Database.DLL
----------------------------------------
CommonTools
    어셈블리 버전: 1.0.1122.2011
    Win32 버전: 1.0.1122.2011
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/CommonTools.DLL
----------------------------------------
MagicLibrary
    어셈블리 버전: 1.7.0.0
    Win32 버전: 1.7.0.0
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/MagicLibrary.DLL
----------------------------------------
System.Windows.Forms.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.3752.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
LiveInformationBox
    어셈블리 버전: 1.0.1122.2011
    Win32 버전: 1.0.1122.2011
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/LiveInformationBox.DLL
----------------------------------------
System.Data.SQLite
    어셈블리 버전: 1.0.97.0
    Win32 버전: 1.0.97.0
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.3752.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
RijndaelEncryptDecrypt
    어셈블리 버전: 1.0.1122.2011
    Win32 버전: 1.0.1122.2011
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/RijndaelEncryptDecrypt.DLL
----------------------------------------
System.Net.Http
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.3752.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.EnterpriseServices
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.3752.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
Win32APIs
    어셈블리 버전: 1.0.1122.2011
    Win32 버전: 1.0.1122.2011
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/Win32APIs.DLL
----------------------------------------
Accessibility
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.3752.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
TextboxRequiredWrapper
    어셈블리 버전: 1.0.1122.2011
    Win32 버전: 1.0.1122.2011
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/TextboxRequiredWrapper.DLL
----------------------------------------
RDPReader
    어셈블리 버전: 1.0.1122.2011
    Win32 버전: 1.0.1122.2011
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/RDPReader.DLL
----------------------------------------
DataProtection
    어셈블리 버전: 1.0.1122.2011
    Win32 버전: 1.0.1122.2011
    코드베이스: file:///X:/Utility/MultiRemoteDesktopClient_2_2/DataProtection.DLL
----------------------------------------

************** JIT 디버깅 **************
JIT(Just In Time) 디버깅을 사용하려면 이 응용 프로그램 또는 컴퓨터의
config 파일(machine.config)의 jitDebugging 값을 
system.windows.forms 섹션에 설정해야 합니다.
또한 응용 프로그램은 디버깅할 수 있도록 컴파일되어야
합니다.

예:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

JIT 디버깅을 사용하면 처리되지 않은 모든 예외는
이 대화 상자에서 처리되지 않고 컴퓨터에 등록된 JIT 
디버거에 보내집니다.

**Comment by jaysonragasa** [comment]
Check 2.3 release  
[https://github.com/jaysonragasa/MultiRDPClient.NET/releases/tag/2.3](https://github.com/jaysonragasa/MultiRDPClient.NET/releases/tag/2.3)

**Comment by jaysonragasa** [comment]
fixed in 2.3 release
