### ISSUE TITLE
I get a exception

### ISSUE THREAD

**Issue by IngoManthey** [jaysonragasa/MultiRDPClient.NET#3]
Hi
I downloaded and unpacked the current version. Then I opened the program and wanted to save a server. I received the following exception:

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.Exception: An error occured while executing a query.
Exception Message: database is locked
database is locked
Stack Trace:
   bei System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   bei System.Data.SQLite.SQLiteDataReader.NextResult()
   bei System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   bei System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   bei System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   bei Database.Database.ExecuteNonQuery(String sql_query, SQLiteParameter[] parameters) in F:\WinForms\MultiRDPClient.NET\Database\Database.cs:Zeile 124.
   bei Database.Servers.Save(ServerDetails server_details) in F:\WinForms\MultiRDPClient.NET\Database\Servers.cs:Zeile 132.
   bei MultiRemoteDesktopClient.ServerSettingsWindow.btnSave_Click(Object sender, EventArgs e) in F:\WinForms\MultiRDPClient.NET\RemoteDesktopClient\Forms\ServerSettingsWindow.cs:Zeile 222.
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4180.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
MultiRemoteDesktopClient
    Assembly-Version: 2.2.0.23940.
    Win32-Version: 2.2.0.0.
    CodeBase: file:///C:/Users/ingo/Downloads/MultiRemoteDesktopClient.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4150.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4001.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
Microsoft.AppCenter.Analytics
    Assembly-Version: 0.0.0.0.
    Win32-Version: 3.2.1.
    CodeBase: file:///C:/Users/ingo/Downloads/Microsoft.AppCenter.Analytics.DLL.
----------------------------------------
Microsoft.AppCenter
    Assembly-Version: 0.0.0.0.
    Win32-Version: 3.2.1.
    CodeBase: file:///C:/Users/ingo/Downloads/Microsoft.AppCenter.DLL.
----------------------------------------
Microsoft.AppCenter.Crashes
    Assembly-Version: 0.0.0.0.
    Win32-Version: 3.2.1.
    CodeBase: file:///C:/Users/ingo/Downloads/Microsoft.AppCenter.Crashes.DLL.
----------------------------------------
Microsoft.VisualBasic
    Assembly-Version: 10.0.0.0.
    Win32-Version: 14.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4180.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
Newtonsoft.Json
    Assembly-Version: 12.0.0.0.
    Win32-Version: 12.0.2.23222.
    CodeBase: file:///C:/Users/ingo/Downloads/Newtonsoft.Json.DLL.
----------------------------------------
SQLitePCLRaw.batteries_v2
    Assembly-Version: 2.0.2.669.
    Win32-Version: 2.0.2.669.
    CodeBase: file:///C:/Users/ingo/Downloads/SQLitePCLRaw.batteries_v2.DLL.
----------------------------------------
netstandard
    Assembly-Version: 2.0.0.0.
    Win32-Version: 4.8.3752.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll.
----------------------------------------
SQLitePCLRaw.core
    Assembly-Version: 2.0.2.669.
    Win32-Version: 2.0.2.669.
    CodeBase: file:///C:/Users/ingo/Downloads/SQLitePCLRaw.core.DLL.
----------------------------------------
SQLitePCLRaw.provider.dynamic_cdecl
    Assembly-Version: 2.0.2.669.
    Win32-Version: 2.0.2.669.
    CodeBase: file:///C:/Users/ingo/Downloads/SQLitePCLRaw.provider.dynamic_cdecl.DLL.
----------------------------------------
System.Memory
    Assembly-Version: 4.0.1.1.
    Win32-Version: 4.6.27617.02.
    CodeBase: file:///C:/Users/ingo/Downloads/System.Memory.DLL.
----------------------------------------
SQLitePCLRaw.nativelibrary
    Assembly-Version: 2.0.2.669.
    Win32-Version: 2.0.2.669.
    CodeBase: file:///C:/Users/ingo/Downloads/SQLitePCLRaw.nativelibrary.DLL.
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll.
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly-Version: 4.0.4.1.
    Win32-Version: 4.6.26919.02.
    CodeBase: file:///C:/Users/ingo/Downloads/System.Runtime.CompilerServices.Unsafe.DLL.
----------------------------------------
System.Management
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll.
----------------------------------------
System.Runtime.Remoting
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll.
----------------------------------------
System.Deployment
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll.
----------------------------------------
System.Deployment.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Deployment.resources/v4.0_4.0.0.0_de_b03f5f7f11d50a3a/System.Deployment.resources.dll.
----------------------------------------
System.Runtime.Serialization
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4180.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
----------------------------------------
System.Numerics
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll.
----------------------------------------
System.Data
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4121.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
Database
    Assembly-Version: 1.0.1122.2011.
    Win32-Version: 1.0.1122.2011.
    CodeBase: file:///C:/Users/ingo/Downloads/Database.DLL.
----------------------------------------
CommonTools
    Assembly-Version: 1.0.1122.2011.
    Win32-Version: 1.0.1122.2011.
    CodeBase: file:///C:/Users/ingo/Downloads/CommonTools.DLL.
----------------------------------------
MagicLibrary
    Assembly-Version: 1.7.0.0.
    Win32-Version: 1.7.0.0.
    CodeBase: file:///C:/Users/ingo/Downloads/MagicLibrary.DLL.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
LiveInformationBox
    Assembly-Version: 1.0.1122.2011.
    Win32-Version: 1.0.1122.2011.
    CodeBase: file:///C:/Users/ingo/Downloads/LiveInformationBox.DLL.
----------------------------------------
System.Data.SQLite
    Assembly-Version: 1.0.97.0.
    Win32-Version: 1.0.97.0.
    CodeBase: file:///C:/Users/ingo/Downloads/System.Data.SQLite.DLL.
----------------------------------------
System.Transactions
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll.
----------------------------------------
RijndaelEncryptDecrypt
    Assembly-Version: 1.0.1122.2011.
    Win32-Version: 1.0.1122.2011.
    CodeBase: file:///C:/Users/ingo/Downloads/RijndaelEncryptDecrypt.DLL.
----------------------------------------
System.Net.Http
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll.
----------------------------------------
System.EnterpriseServices
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll.
----------------------------------------
Win32APIs
    Assembly-Version: 1.0.1122.2011.
    Win32-Version: 1.0.1122.2011.
    CodeBase: file:///C:/Users/ingo/Downloads/Win32APIs.DLL.
----------------------------------------
TextboxRequiredWrapper
    Assembly-Version: 1.0.1122.2011.
    Win32-Version: 1.0.1122.2011.
    CodeBase: file:///C:/Users/ingo/Downloads/TextboxRequiredWrapper.DLL.
----------------------------------------

************** JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

I try to import a RDP file here I get follow exception:
Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.Exception: An error occured while executing a query.
Exception Message: constraint failed
UNIQUE constraint failed: Servers.servername
Stack Trace:
   bei System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   bei System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   bei System.Data.SQLite.SQLiteDataReader.NextResult()
   bei System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   bei System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   bei System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   bei Database.Database.ExecuteNonQuery(String sql_query, SQLiteParameter[] parameters) in F:\WinForms\MultiRDPClient.NET\Database\Database.cs:Zeile 124.
   bei Database.Servers.Save(ServerDetails server_details) in F:\WinForms\MultiRDPClient.NET\Database\Servers.cs:Zeile 132.
   bei MultiRemoteDesktopClient.ImportWindow.btnStart_Click(Object sender, EventArgs e) in F:\WinForms\MultiRDPClient.NET\RemoteDesktopClient\Forms\ImportWindow.cs:Zeile 138.
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)

What can I do?

regards Ingo

**Comment by jaysonragasa** [comment]
This is confirmed and the SqLite provider has been problematic. Will be changing how data source is handled soon.

**Comment by jaysonragasa** [comment]
Check 2.3 release  
[https://github.com/jaysonragasa/MultiRDPClient.NET/releases/tag/2.3](https://github.com/jaysonragasa/MultiRDPClient.NET/releases/tag/2.3)

**Comment by jaysonragasa** [comment]
fixed in 2.3 release
